// RTC.h: interface for the CRTC class.
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_RTC_H__74EF8D61_62B4_11D6_AFEE_00A0B003CEAC__INCLUDED_)
#define AFX_RTC_H__74EF8D61_62B4_11D6_AFEE_00A0B003CEAC__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

class CRTC  
{
public:
	CRTC();
	virtual ~CRTC();

};

#endif // !defined(AFX_RTC_H__74EF8D61_62B4_11D6_AFEE_00A0B003CEAC__INCLUDED_)
