

// Message


enum FORM_TYPE { WND_SPLITTER_HORIZONTAL,WND_SPLITTER_VERTICAL, WND_SPLITTER_MAX };


#define GET_CMD_PANEL(X)		( (X/10)*10)

enum Enum_FORM_ID
{
	FORM_ID_TITLE_PANEL					= 1,
	FORM_ID_M_NAVI_PANEL				= 2,

	
	FORM_ID_CMD_OPERATION				= 10,
	FORM_ID_INFOR_MAIN					= 11,
	FORM_ID_INFOR_RECIPE				= 12,
	FORM_ID_INFOR_MES					= 13,
	FORM_ID_INFOR_PARA					= 14,
	FORM_ID_INFOR_SETUP					= 15,
	FORM_ID_INFOR_MCSTATUS				= 16,

	FORM_ID_INFOR_OPERATION				= 17,

	FORM_ID_CMD_RECIPE					= 20,

	FORM_ID_CMD_MANUAL					= 30,
	FORM_ID_INFOR_MANUAL_LASER			= 33,
	FORM_ID_INFOR_MANUAL_SCANNER		= 34,

	FORM_ID_CMD_SETUP					= 40,
	FORM_ID_INFOR_SETUP_LASER			= 42,
	FORM_ID_INFOR_SETUP_IO				= 43,

	FORM_ID_CMD_LOG						= 50,
	FORM_ID_INFOR_LOG					= 51,
	FORM_ID_INFOR_JAM					= 52,
};

