//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// Options.rc에서 사용되고 있습니다.
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_OPTIONS_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDD_LASER_SOURCE                129
#define IDD_VIEW_DIALOG                 130
#define IDD_LOG_DIALOG                  131
#define IDD_DIR_DIALOG                  132
#define IDB_DRIVES                      133
#define IDD_PARA_DIALOG                 133
#define IDD_DIALOG_AMKORDIR_SET         134
#define IDC_CHK_DEFAULTFILE             1001
#define IDC_CHK_NETWORK                 1002
#define IDC_DSP_FILE                    1003
#define IDC_FIELD_SCALE                 1003
#define IDC_CHK_HKIMAGE                 1004
#define IDC_CHK_LOADIMAGE               1005
#define IDC_MM                          1006
#define IDC_FIELD                       1007
#define IDC_POINT                       1008
#define IDC_MIL                         1009
#define IDC_FIELD_ANGLE                 1010
#define IDC_LASER_SELECT                1011
#define IDC_MAX_FIELD                   1012
#define IDC_MAX_MM                      1013
#define IDC_TWO_PART                    1014
#define IDC_CHIP_SELECT                 1015
#define IDC_QUANTRONIX                  1015
#define IDC_SHUTTER                     1016
#define IDC_ROFIN                       1016
#define IDC_MASTER_X                    1017
#define IDC_HANA                        1017
#define IDC_LEE                         1018
#define IDC_COUNT                       1018
#define IDC_MASTER_Y                    1019
#define IDC_COHERENT                    1019
#define IDC_SLAVE_X                     1020
#define IDC_IPGFIBER                    1020
#define IDC_SLAVE_Y                     1021
#define IDC_SPIFIBER                    1021
#define IDC_SINGLE_HEAD                 1022
#define IDC_STATIC_LASER                1022
#define IDC_DUAL_HEAD                   1023
#define IDC_YAG                         1024
#define IDC_COL_DEVINNER                1024
#define IDC_CO2                         1025
#define IDC_VIEW_OPTION                 1025
#define IDC_COL_DEVOUTER                1025
#define IDC_COL_DEVLINE                 1026
#define IDC_LOG_OPTION                  1026
#define IDC_BICRONIX                    1026
#define IDC_COL_GRIDLINE                1027
#define IDC_SEL_PARA_COLOR              1027
#define IDC_JDSU                        1027
#define IDC_PIC_DEVINNER                1028
#define IDC_LASERVALL                   1028
#define IDC_PIC_DEVOUTER                1029
#define IDC_YAG2                        1029
#define IDC_PIC_DEVLINE                 1030
#define IDC_YAG3                        1030
#define IDC_PIC_GRIDLINE                1031
#define IDC_YAG4                        1031
#define IDC_NOUSE                       1031
#define IDC_COL_GRIDSCALE               1032
#define IDC_PARA_11                     1032
#define IDC_PIC_GRIDSCALE               1033
#define IDC_COL_RULER                   1034
#define IDC_PARA_8                      1034
#define IDC_PIC_RULER                   1035
#define IDC_COL_SELBOX                  1036
#define IDC_PARA_9                      1036
#define IDC_PIC_SELBOX                  1037
#define IDC_PARA_10                     1038
#define IDC_SIZE_SELBOX                 1039
#define IDC_PARA_12                     1039
#define IDC_SIZE_RULERFONT              1040
#define IDC_AUTO_START                  1040
#define IDC_PARA_13                     1040
#define IDC_SIZE_RULER                  1041
#define IDC_AUTO_END                    1041
#define IDC_PARA_14                     1041
#define IDC_SIZE_RULERSCALE             1042
#define IDC_AUTO_END_EVENT              1042
#define IDC_PARA_15                     1042
#define IDC_MANUAL_START                1043
#define IDC_PARA_16                     1043
#define IDC_MANUAL_END                  1044
#define IDC_PARA_17                     1044
#define IDC_WAIT_START                  1045
#define IDC_PARA_18                     1045
#define IDC_WAIT_END                    1046
#define IDC_PARA_19                     1046
#define IDC_LASER_ERROR                 1047
#define IDC_PARA_20                     1047
#define IDC_CODE_AUTOSTART              1048
#define IDC_PARA_21                     1048
#define IDC_CODE_AUTOEND                1049
#define IDC_CODE_AUTOENDEVENT           1050
#define IDC_CODE_MANUALSTART            1051
#define IDC_CODE_MANUALEND              1052
#define IDC_CODE_WAITSTART              1053
#define IDC_CODE_WAITEND                1054
#define IDC_CODE_LASERERROR             1055
#define IDC_DIRECTORY                   1056
#define IDC_SAVE_DIR                    1057
#define IDC_SAVE_PERIOD                 1058
#define IDC_SEL_DIR                     1059
#define IDC_PARA_1                      1060
#define IDC_PARA_2                      1061
#define IDC_PARA_3                      1062
#define IDC_PARA_4                      1063
#define IDC_PARA_5                      1064
#define IDC_PARA_6                      1065
#define IDC_PARA_7                      1066
#define IDC_PARA_COLOR                  1067
#define IDC_SAME_RATIO                  1068
#define IDC_RADIO1                      1068
#define IDC_SPECTRON                    1068
#define IDC_CHECK_AMKOR                 1070
#define IDC_EDIT_EDIT_DIR               1071
#define IDC_EDIT_FONT_DIR               1072
#define IDC_EDIT_RSC_DIR                1073
#define IDC_EDIT_HPGL_DIR               1074
#define IDC_EDIT_TMP_DIR                1075
#define IDC_EDIT_PRJ_DIR                1076
#define IDC_BUTTON_EDITDIR              1077
#define IDC_BUTTON_RSC_DIR              1078
#define IDC_BUTTON_FONT_DIR             1079
#define IDC_BUTTON_HPGL_DIR             1080
#define IDC_BUTTON_TMP_DIR              1081
#define IDC_BUTTON_PRJ_DIR              1082
#define IDC_EDIT_FIELD_SET              1083
#define IDC_STATIC_FIELD                1084
#define IDC_EDIT_COMPANY                1085
#define IDC_EDIT_COMPANYCODE            1085
#define IDC_STATIC_COMPANY              1086
#define IDC_EDIT_POWER_N                1086
#define IDC_EDIT_SITECODE               1086
#define IDC_EDIT_HEAD1_NAME             1086
#define IDC_EDIT_POWER_L                1087
#define IDC_EDIT_PEN_DIR                1087
#define IDC_EDIT_POWER_M                1088
#define IDC_BUTTON_PEN_DIR              1088
#define IDC_CHECK_IMAGE                 1090
#define IDC_EDIT_SPECIMAGE_FOLDER       1091
#define IDC_BUTTON_DIR                  1092
#define IDC_MODE_CIR                    1094
#define IDC_SCANLAB                     1094
#define IDC_MODE_CONTINE                1095
#define IDC_3RDEYE                      1095
#define IDC_SCALE                       1096

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1097
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
