#if !defined(AFX_CTCHECK_H__358C8591_AB51_11D5_8C03_000296009500__INCLUDED_)
#define AFX_CTCHECK_H__358C8591_AB51_11D5_8C03_000296009500__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CctCheck wrapper class

class CctCheck : public CWnd
{
protected:
	DECLARE_DYNCREATE(CctCheck)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x2b701ea6, 0xb8d5, 0x11d4, { 0xa8, 0x5d, 0x0, 0x80, 0xc8, 0xdf, 0xc8, 0x81 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	BOOL GetEnabled();
	void SetEnabled(BOOL);
	LPFONTDISP GetFont();
	void SetFont(LPFONTDISP);
	CString GetCaption();
	void SetCaption(LPCTSTR);
	OLE_HANDLE GetHWnd();
	void SetHWnd(OLE_HANDLE);
	short Get_Value();
	void Set_Value(short);
	unsigned long GetBackColor();
	void SetBackColor(unsigned long);
	unsigned long GetForeColor();
	void SetForeColor(unsigned long);
	LPDISPATCH GetPictureTrue();
	void SetPictureTrue(LPDISPATCH);
	LPDISPATCH GetPictureFalse();
	void SetPictureFalse(LPDISPATCH);
	long GetPicStyle();
	void SetPicStyle(long);
	long GetAlignment();
	void SetAlignment(long);
	unsigned long GetDisableColor();
	void SetDisableColor(unsigned long);
	BOOL GetShowFocus();
	void SetShowFocus(BOOL);
	BOOL GetChecked();
	void SetChecked(BOOL);
	LPDISPATCH GetBackImage();
	void SetBackImage(LPDISPATCH);
	short GetImageXOffset();
	void SetImageXOffset(short);
	short GetImageYOffset();
	void SetImageYOffset(short);
	unsigned long GetForeColorOver();
	void SetForeColorOver(unsigned long);
	LPDISPATCH GetFontOver();
	void SetFontOver(LPDISPATCH);
	BOOL GetCheckMouseOver();
	void SetCheckMouseOver(BOOL);
	LPDISPATCH GetMouseIcon();
	void SetMouseIcon(LPDISPATCH);
	BOOL GetMaskBitmap();
	void SetMaskBitmap(BOOL);
	unsigned long GetMaskColor();
	void SetMaskColor(unsigned long);
	long GetValue();
	void SetValue(long);
	LPDISPATCH GetPictureGrey();
	void SetPictureGrey(LPDISPATCH);
	long GetMousePointer();
	void SetMousePointer(long);

// Operations
public:
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CTCHECK_H__358C8591_AB51_11D5_8C03_000296009500__INCLUDED_)
