#if !defined(AFX_CTDIGIT_H__067ED9E2_BCA5_11D5_8C03_000296009500__INCLUDED_)
#define AFX_CTDIGIT_H__067ED9E2_BCA5_11D5_8C03_000296009500__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CctDigit wrapper class

class CctDigit : public CWnd
{
protected:
	DECLARE_DYNCREATE(CctDigit)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xafbf4626, 0x9fdb, 0x11d5, { 0xa8, 0x5e, 0x0, 0x80, 0xc8, 0xdf, 0xc8, 0x81 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	BOOL GetEnabled();
	void SetEnabled(BOOL);
	CString GetText();
	void SetText(LPCTSTR);
	unsigned long GetBackColor();
	void SetBackColor(unsigned long);
	LPDISPATCH GetBackImage();
	void SetBackImage(LPDISPATCH);
	short GetImageXOffset();
	void SetImageXOffset(short);
	short GetImageYOffset();
	void SetImageYOffset(short);
	long GetAlignment();
	void SetAlignment(long);
	short GetDigitWidth();
	void SetDigitWidth(short);
	long GetBorderType();
	void SetBorderType(long);
	unsigned long GetBorderColor();
	void SetBorderColor(unsigned long);
	long GetMousePointer();
	void SetMousePointer(long);
	LPDISPATCH GetMouseIcon();
	void SetMouseIcon(LPDISPATCH);
	unsigned long GetForeColor();
	void SetForeColor(unsigned long);
	long GetHWnd();
	void SetHWnd(long);
	short GetLineWidth();
	void SetLineWidth(short);
	short GetHeightMargin();
	void SetHeightMargin(short);
	short GetWidthMargin();
	void SetWidthMargin(short);
	short GetLineMargin();
	void SetLineMargin(short);
	unsigned long GetDisableColor();
	void SetDisableColor(unsigned long);

// Operations
public:
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CTDIGIT_H__067ED9E2_BCA5_11D5_8C03_000296009500__INCLUDED_)
