#if !defined(AFX_CTMETER_H__358C859A_AB51_11D5_8C03_000296009500__INCLUDED_)
#define AFX_CTMETER_H__358C859A_AB51_11D5_8C03_000296009500__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CctMeter wrapper class

class CctMeter : public CWnd
{
protected:
	DECLARE_DYNCREATE(CctMeter)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x5a1b36c6, 0xcb42, 0x11d4, { 0xa1, 0xff, 0x0, 0xe0, 0x98, 0x85, 0x64, 0x12 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	BOOL GetEnabled();
	void SetEnabled(BOOL);
	LPFONTDISP GetFont();
	void SetFont(LPFONTDISP);
	OLE_HANDLE GetHWnd();
	void SetHWnd(OLE_HANDLE);
	CString GetCaption();
	void SetCaption(LPCTSTR);
	unsigned long GetBackColor();
	void SetBackColor(unsigned long);
	unsigned long GetForeColor();
	void SetForeColor(unsigned long);
	long GetBorderType();
	void SetBorderType(long);
	long GetMeterStyle();
	void SetMeterStyle(long);
	unsigned long GetShadowColor();
	void SetShadowColor(unsigned long);
	unsigned long GetBorderColor();
	void SetBorderColor(unsigned long);
	long GetValue();
	void SetValue(long);
	long GetMinValue();
	void SetMinValue(long);
	long GetMaxValue();
	void SetMaxValue(long);
	BOOL GetDisplayText();
	void SetDisplayText(BOOL);
	long GetMeterValue();
	void SetMeterValue(long);
	BOOL GetUseCaption();
	void SetUseCaption(BOOL);
	long GetAlignment();
	void SetAlignment(long);
	BOOL GetThinBorder();
	void SetThinBorder(BOOL);
	long GetDisplayStyle();
	void SetDisplayStyle(long);
	LPDISPATCH GetBackImage();
	void SetBackImage(LPDISPATCH);
	short GetImageXOffset();
	void SetImageXOffset(short);
	short GetImageYOffset();
	void SetImageYOffset(short);
	short GetBlockSize();
	void SetBlockSize(short);
	short GetBlockMargin();
	void SetBlockMargin(short);
	BOOL GetSquareBlocks();
	void SetSquareBlocks(BOOL);
	unsigned long GetChangeColor();
	void SetChangeColor(unsigned long);
	short GetChangeValue();
	void SetChangeValue(short);
	unsigned long GetTextColor();
	void SetTextColor(unsigned long);

// Operations
public:
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CTMETER_H__358C859A_AB51_11D5_8C03_000296009500__INCLUDED_)
